# Generated by Django 3.1.7 on 2021-03-27 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('login', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=65)),
                ('role', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('patronymic', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.auth')),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bio')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('pet_photo', models.CharField(max_length=36)),
                ('result_photo', models.CharField(max_length=36)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
    ]
