# Generated by Django 3.1 on 2021-04-12 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
                ('role', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('patronymic', models.CharField(default='', max_length=128, null=True)),
                ('phone', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('bytes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.auth')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.personaldata')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('pet_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_photo_fk', to='rest.photo')),
                ('result_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_photo_fk', to='rest.photo')),
            ],
        ),
    ]
