# Generated by Django 3.1 on 2021-04-09 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('login', models.CharField(db_index=True, max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('patronymic', models.CharField(max_length=64, null=True)),
                ('phone', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.auth')),
                ('personal_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.personaldata')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('pet_name', models.CharField(db_index=True, max_length=64)),
                ('pet_photo', models.CharField(max_length=36)),
                ('result_photo', models.CharField(max_length=36)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.user')),
            ],
        ),
    ]
