# Generated by Django 3.1.7 on 2021-03-26 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthData',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=16, unique=True)),
                ('role', models.IntegerField()),
                ('password', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=256)),
                ('pet_photo', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('patronymic', models.CharField(max_length=256)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session1.authdata')),
            ],
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Riddle',
        ),
        migrations.AddField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session1.user'),
        ),
    ]
